site_name: EvoProtGrad
site_description: The documentation for the EvoProtGrad library.
site_author: Patrick Emami
site_url: https://nrel.github.io/EvoProtGrad

repo_name: NREL/EvoProtGrad
repo_url: https://github.com/NREL/EvoProtGrad/

theme:
  name: material
  features:
      - navigation.sections  # Sections are included in the navigation on the left.
      - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
      - header.autohide  # header disappears as you scroll
plugins:
  - search
  - autorefs  # Cross-links to headings
  - mkdocstrings:
      handlers:
          python:
            selection:
                inherited_members: true  # Allow looking up inherited methods
            rendering:
                show_root_heading: true  # actually display anything at all...
                show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                show_signature_annotations: true
                show_source: false  # don't include source code
                members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                heading_level: 4
nav: 
  - index.md
  - Getting Started:
    - getting_started/installation.md
    - getting_started/Trying_out_EvoProtGrad.md
    - getting_started/experts.md
    - getting_started/MCMC.md
    - getting_started/tokenizers.md
  - API: 
    - api/evo_prot_grad.md
    - api/models.md
    - api/experts.md
    - evo_prot_grad.common:
      - api/common/embeddings.md
      - api/common/sampler.md
      - api/common/tokenizers.md
      - api/common/utils.md
      - api/common/variant_scoring.md
      
extra_css:
    - css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: ''
      toc_depth: 1-2  
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js